Aula 4 - Manipulação de Dados
guia-de-sobrevivencia-do-programador/Notas-de-Aula pull request #15
Opened 2022-02-01 22:22 UTC by matiasvinicius

Manipulações básicas de dados usando o terminal, regex e APIs

- [x] Conteúdo
- [ ] Tarefas

2022-02-02 21:56 UTC, cordeiro reviewed
Correção de alguns typos

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +- `[A-Z][a-z]{2}`: Três caracteres agora, o primeiro em maiúscula e os dois seguintes (extados dois) em letra minuscula;
```suggestion
- `[A-Z][a-z]{2}`: Três caracteres agora, o primeiro em maiúscula e os dois seguintes (exatos dois) em letra minúscula;
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +O comando `sed` (Editor de Streams/Fluxo)funciona como um editor de texto para o Linux, sendo utilizado essencialmente para filtragem de texto. Isso quer dizer que ele é uma ótima ferramenta para lim
```suggestion
O comando `sed` (Editor de Streams/Fluxo) funciona como um editor de texto para o Linux, sendo utilizado essencialmente para filtragem de texto. Isso quer dizer que ele é uma ótima ferramenta para limpar textos e, consequentemente, sumarizar dados para trazer mais informação.
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +- `[0-9]{4}`: Extamante quatro dígitos para representar o ano;
```suggestion
- `[0-9]{4}`: Exatamente quatro dígitos para representar o ano;
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +Com isso é possível perceber que aproximadamente 32 % das requisições falharam.
```suggestion
Com isso é possível perceber que aproximadamente 32% das requisições falharam.
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +Você pode passar os arquivos gerados para outras linguagens de programação mais poderosas para análise de dados como Python e R. Veja um exemplo com python onde capturamos todos os IPs e vemos a dist
```suggestion
Você pode passar os arquivos gerados para outras linguagens de programação mais poderosas para análise de dados como Python e R. Veja um exemplo com Python onde capturamos todos os IPs e vemos a distribuição de probabilidade correspondente ao número de requisições feitas em um dia:
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +Mas `awk` é muito poderos mesmo, você pode facilmente interagir com seus arquivos ou sistema operacional da maneira que quiser (e que conseguir implementar)! Vamos usar o comando `ls -la`  com o `awk
```suggestion
Mas `awk` é muito poderoso mesmo, você pode facilmente interagir com seus arquivos ou sistema operacional da maneira que quiser (e que conseguir implementar)! Vamos usar o comando `ls -la`  com o `awk` e filtrar a hora em que cada arquivo da pasta corrente foi alterado:
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +Você também pode sgerar estatísticas usando por exemplo R (que é outra linguagem de programação) podendo fazer tudo direto como entrada pelo terminal:
```suggestion
Você também pode gerar estatísticas usando por exemplo R (que é outra linguagem de programação) podendo fazer tudo direto como entrada pelo terminal:
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +API (Interface de programação de aplicações) é uma maneira muito utilizada atualmente por programadores e pessoas que extraem dados de maneira geral na web. Uma API pode ser imaginada como um sistema
```suggestion
API (interface de programação de aplicações) é uma maneira muito utilizada atualmente por programadores e pessoas que extraem dados de maneira geral na web. Uma API pode ser imaginada como um sistema, mais especificamente uma interface, desenvolvida para permitir que pessoas que tenham acesso à API de capturar dados ou utilizar os serviços disponibilizados.
```

2022-02-02 21:56 UTC, cordeiro commented on 4 - Manipulação De Dados/README.md
> +Caso queira retornar por exemplo apenas os CEPS de todas as localidades que batem com o endereço você pode usar`jq` também. Perceba que há um padrão: `[{informações},{informações...{informações}]`. C
```suggestion
Caso queira retornar, por exemplo, apenas os CEPS de todas as localidades que batem com o endereço você pode usar `jq` também. Perceba que há um padrão: `[{informações},{informações...{informações}]`. Com o `jq` fica assim a leitura dos CEPs:
```

2022-02-03 04:33 UTC, matiasvinicius commented
> Correção de alguns typos

Correções feitas :)

2022-02-03 18:13 UTC, JoaoFukuda requested changes
So tem coisinha, mas a aula em si ta incrivel!

2022-02-03 18:13 UTC, fnknda commented on 4 - Manipulação De Dados/README.md
> +O trabalho do `grep` foi muito útil para identificar padrões e extraí-los, mas e se nosso intuíto fosse modificar os textos a fim de gerar novos arquivos ou mesmo reduzir a quantidade de dados e gera
```suggestion
O trabalho do `grep` foi muito útil para identificar padrões e extraí-los, mas e se nosso intuíto fosse modificar os textos a fim de gerar novos arquivos ou até mesmo reduzir a quantidade de dados e gerar mais informação? Neste caso a ferramenta que tenderá a ter mais utilidade que o `grep` é o `sed`.
```

2022-02-03 18:13 UTC, JoaoFukuda commented on 4 - Manipulação De Dados/tarefa/README.md
> +Neste exercício temos uma linha de texto no arquivo `cifra.txt` que foi criptografada utilizando o método de substituição. Sua tarefa é utilizar o comando `grep` e quando necessário expressões regula
```suggestion
Neste exercício temos uma linha de texto no arquivo `cifra.txt` que foi criptografada utilizando o método de substituição. Sua tarefa é utilizar o comando `grep` e, quando necessário, expressões regulares para gerar uma tabela que contém na primeira coluna a frequência de aparições de um caractere, e na segunda coluna o caractere que está fazendo referência. Obviamente você também pode utilizar outros comandos como o `uniq` para esta tarefa, mas **deve** utilizar o comando `grep`. A tabela final pode ser ordenada da maneira que preferir, desde que contenha todas as referências de caracteres.
```

2022-02-03 18:13 UTC, JoaoFukuda commented on 4 - Manipulação De Dados/tarefa/README.md
> +```"Mozilla/5.0 (Windows NT 6.1; rv:17.0) Gecko/17.0 Firefox/17.0"```
```suggestion
`"Mozilla/5.0 (Windows NT 6.1; rv:17.0) Gecko/17.0 Firefox/17.0"`
```

2022-02-03 18:13 UTC, JoaoFukuda commented on 4 - Manipulação De Dados/tarefa/README.md
> +Escolha uma API que não seja a viacep e faça uma requisição `GET` usando o `curl`. Você pode escolher APIs de acesso público como a [PokéAPI](https://pokeapi.co/) e a [Randomuser.me](https://randomus
```suggestion
Escolha uma API que não seja a viacep e faça uma requisição `GET` usando o `curl`. Você pode escolher APIs de acesso público como a [PokéAPI](https://pokeapi.co/) e a [Randomuser.me](https://randomuser.me/) , ou restritas por credenciais como a do [Spotify](https://developer.spotify.com/documentation/web-api/) e a do [Twitter](https://developer.twitter.com/en/docs/twitter-api). Caso escolha fazer uma requisição em uma API privada você **não precisa e nem deve** enviar suas chaves de acesso no comando que acompanha a tarefa (pode escrever algo como `<chave_api>` no lugar). 
```

2022-02-03 18:13 UTC, JoaoFukuda commented on 4 - Manipulação De Dados/tarefa/README.md
> +Salve o retorno da API em um arquivo chamado `3.txt`. Caso veja que há informações sensíveis no retorno, pode sustituí-las no arquivo final por <removido_para_entrega> onde achar pertinente.
```suggestion
Salve o retorno da API em um arquivo chamado `3.txt`. Caso veja que há informações sensíveis no retorno, pode sustituí-las no arquivo final por `<removido_para_entrega>` onde achar pertinente.
```

2022-02-03 18:27 UTC, JoaoFukuda approved these changes

2022-02-03 18:27 UTC, merged